// File generated by FlutterFire CLI.
// ignore_for_file: type=linti
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-jnWc2IOu_y5nVvWGS5zbjsJfuk2Jj0',
    appId: '1:767867066586:web:fa15310695a6ea48acade3',
    messagingSenderId: '767867066586',
    projectId: 'marketi-26028',
    authDomain: 'marketi-26028.firebaseapp.com',
    storageBucket: 'marketi-26028.firebasestorage.app',
    measurementId: 'G-KSP10FNVLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs6oZm-7zvJ3y-OfB9Mq233rX7aP76H5A',
    appId: '1:767867066586:android:d3fbe054c78e46caacade3',
    messagingSenderId: '767867066586',
    projectId: 'marketi-26028',
    storageBucket: 'marketi-26028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAlGTBuTr_TB4h4ltUeXj4Mn0AE51cWJw',
    appId: '1:767867066586:ios:298dd5ddb234866eacade3',
    messagingSenderId: '767867066586',
    projectId: 'marketi-26028',
    storageBucket: 'marketi-26028.firebasestorage.app',
    iosBundleId: 'com.example.marketiECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAlGTBuTr_TB4h4ltUeXj4Mn0AE51cWJw',
    appId: '1:767867066586:ios:298dd5ddb234866eacade3',
    messagingSenderId: '767867066586',
    projectId: 'marketi-26028',
    storageBucket: 'marketi-26028.firebasestorage.app',
    iosBundleId: 'com.example.marketiECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt-jnWc2IOu_y5nVvWGS5zbjsJfuk2Jj0',
    appId: '1:767867066586:web:7a48d2b64f565fb8acade3',
    messagingSenderId: '767867066586',
    projectId: 'marketi-26028',
    authDomain: 'marketi-26028.firebaseapp.com',
    storageBucket: 'marketi-26028.firebasestorage.app',
    measurementId: 'G-PP8EE2RWVY',
  );
}
